### ISSUE TITLE
[question] How does it compare to postcss-color-function?

### ISSUE THREAD

**Issue by stefanmaric** [jonathantneal/postcss-color-mod-function#10]
Hi,

I've been using [postcss/postcss-color-function](https://github.com/postcss/postcss-color-function) for long time but it seems a bit stale regarding the standard draft.

I would like to know how does this project compare to postcss-color-function? Any suggestions about migration?

Thanks ♥

**Comment by jonathantneal** [comment]
Hi @stefanmaric,

There are two things to watch for when switching to this project:

1. The function is named `color-mod` and not `color`, so update those function names accordingly.
2. CSS Variables cannot be fully supported, so they will attempt to resolve from `:root`.

Does this help?

**Comment by jonathantneal** [comment]
@stefanmaric, good news; this plugin won’t run into issues with [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) (which I’ve also been maintaining). As for postcss-color-function, I do hope they can resolve those issues, along with the name (it was changed _years_ ago). Those were the reasons I had to create this project.

I’d be open to a PR for documentation changes, only because I can’t think of what I’d say, and I don’t presently know how people are migrating to this plugin outside of [postcss-preset-env](https://github.com/jonathantneal/postcss-preset-env). I hope that doesn’t sound too lazy, but if it does and the documentation seems pretty important, then I really would still appreciate a PR. 😄

Also, let me know if you think your original issue has been resolved. If not, of course feel free to keep pinging me and I’ll answer you when a break appears.

**Comment by stefanmaric** [comment]
> Also, let me know if you think your original issue has been resolved. If not, of course feel free to keep pinging me and I’ll answer you when a break appears.

I gave it a shot and migrated a fairly big project in a snap; as you said, just a matter of swapping the plugins and rename `color() -> color-mod()`. I haven't found any issues so far. :tada: 

> I don’t presently know how people are migrating to this plugin outside of postcss-preset-env.

Indeed. Probably few people cherry pick postcss plugins and use cssnext or postcss-preset-env instead.
